blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='comment/', view=views.comment, name='comment'),
    path(route='search/', view=views.search, name='search'),
    path(route='update-blogs/', view=views.updateBlogs, name='update_blogs'),
    # path(route='hashnode-blogs', view=views.hashnodeBlogs, name='hashnode_blogs'), 
]

dataidea/urls.py
from django.urls import path
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path(route = 'admin/', view=admin.site.urls),
    path(route='', view=include('index.urls'), name='index'),
    path(route='blog/', view=include('blog.urls'), name='blog'),
    path(route='school/', view=include('school.urls'), name='school'),
    path(route='profiles/', view=include('profiles.urls'), name='profiles'),
    path(route='accounts/', view=include('accounts.urls'), name='accounts'),
    path(route='tools/', view=include('tools.urls'), name='tools')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path(route='transcriber/upload/', view=views.upload_file, name='upload_transcribe_file'),
    path(route='transcriber/download/<int:pk>/<str:option>/', view=views.download_transcription, name='download_transcription'),
    path(route='note/add_note/', view=views.add_note, name='add_note'),
    path(route='note/delete_note/<int:id>', view=views.delete_note, name='delete_note'),
    path(route='note/one_note/<int:id>', view=views.one_note, name='one_note'),
]

tools/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Transcription(models.Model):
    audio_file = models.FileField(upload_to='audio_files/')
    transcription_text = models.TextField(blank=True)
    summary_text = models.TextField(blank=True)

    def __str__(self):
        return self.audio_file
    

class Note(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, default='Note Title')
    detail = models.TextField(default='Note Detail')
    date_created = models.DateField(auto_now=True)
    def __str__(self):
        return f'{self.user.username}, {self.title}'

tools/forms.py
from django import forms

TRANSCRIPT_OPTIONS = [
    ('transcript', 'Transcript Only'),
    ('summary', 'Summary Only'),
]

class AudioUploadForm(forms.Form):
    audio_file = forms.FileField(
        label='Select an audio file (max size: 25MB)',
        required=True,
        widget=forms.ClearableFileInput(attrs={'accept': 'audio/*'}),
    )

class TranscriptionOptionsForm(forms.Form):
    transcript_option = forms.ChoiceField(
        label='Select Transcription Option',
        choices=TRANSCRIPT_OPTIONS,
        required=True,
        widget=forms.RadioSelect,
    )

tools/views.py
import assemblyai as aai
from .models import Note
from .models import Transcription
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from .forms import AudioUploadForm, TranscriptionOptionsForm

aai.settings.api_key = f"3282ce6eca0a47519f6f69dbbaa38da6"

@login_required(login_url='accounts:signin')
def upload_file(request):
    if request.method == 'POST':
        audio_form = AudioUploadForm(request.POST, request.FILES)
        options_form = TranscriptionOptionsForm(request.POST)

        if audio_form.is_valid() and options_form.is_valid():
            audio_file = audio_form.cleaned_data['audio_file']
            transcript_option = options_form.cleaned_data['transcript_option']

            # Save the uploaded audio file
            transcription = Transcription(audio_file=audio_file)
            transcription.save()

            # Transcribe the audio file
            transcriber = aai.Transcriber()
            transcript = transcriber.transcribe(
            data=transcription.audio_file.path,
            config= aai.TranscriptionConfig(
                summarization= True,
                summary_model=aai.SummarizationModel.informative,
                summary_type=aai.SummarizationType.bullets
            ))

            transcription.summary_text = transcript.summary
            transcription.transcription_text = transcript.text
            # Save transcription
            transcription.save()


            return redirect(to='download_transcription',
                            pk=transcription.pk,
                            option='text' if transcript_option == 'text' else 'summary')




    else:
        audio_form = AudioUploadForm()
        options_form = TranscriptionOptionsForm()

    return render(request, 'tools/upload.html', {'audio_form': audio_form, 'options_form': options_form})

def download_transcription(request, pk, option):
    transcription = Transcription.objects.get(pk=pk)
    response = HttpResponse(content_type='text/plain')

    if option == 'text':
        response['Content-Disposition'] = f'attachment; filename="transcription_text.txt"'
        response.write(transcription.transcription_text)
    else:
        response['Content-Disposition'] = f'attachment; filename="transcription_summary.txt"'
        response.write(transcription.summary_text)
    return response


# Notes Section
@login_required(login_url='accounts:signin')
def add_note(request):
    if request.method == 'POST':
        title = request.POST.get(key='title')
        detail = request.POST.get(key='detail')
        note = Note(title=title, detail=detail, user=request.user)
        note.save()
        return redirect(request.META.get('HTTP_REFERER'))
    else:
        user_notes = Note.objects.filter(user = request.user)
        template_name = 'tools/notes.html'
        context = {'notes': user_notes}
        return render(request=request, template_name=template_name, context=context)

@login_required(login_url='accounts:signin')
def one_note(request, id):
    try:
        note = Note.objects.get(id=id)
        if request.method == 'POST':
            title = request.POST.get(key='title')
            detail = request.POST.get(key='detail')
            note = Note(title=title, detail=detail, user=request.user)
            note.save()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            template_name = 'tools/note_detail.html'
            context = {'note': note}
            return render(request=request, template_name=template_name, context=context)
    except Note.DoesNotExist as dne:
        context = {'state': 'danger', 'message': 'Note does not exist!'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)
    except Exception as e:
        context = {'state': 'danger', 'message': 'An error occured while trying to fetch the note'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)


@login_required(login_url='accounts:signin')
def delete_note(request, id):
    try:
        note = Note.objects.get(id=id)
        note.delete()
        return redirect(to='tools:add_note')
    except Note.DoesNotExist as dne:
        context = {'state': 'warning', 'message': 'Note does not exist!'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)
    except Exception as e:
        context = {'state': 'warning', 'message': 'An error occured while trying to delete the note'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)

tools/templates/tools/download.html
<h1>Transcription Result</h1>
    <p>You can download your transcription below:</p>
    <a href="{{ download_url }}" download="transcription.txt">Download Transcription</a>

tools/templates/tools/note_detail.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="p-2">Note Details</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><span>Services</span></li>
          <li><span>Tools</span></li>
          <li><span>Notes</span></li>
          <li>Details</li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-8">
          <div class="container">
            <h4>{{note.title}}</h4>
            <pre class="p-3" style="background: whitesmoke">
              <p>{{note.detail}}</p>
            </pre>
            <a
              class="btn btn-danger"
              href="{% url 'tools:delete_note' note.id %}"
            >
              Delete
            </a>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="portfolio-info">
            <h3>Note information</h3>
            <ul>
              <li><strong>Date created</strong>: {{note.date_created}}</li>
              <li><strong>Created by</strong>: {{note.user.username}}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Portfolio Details Section -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
</script>

{% endblock %}

tools/templates/tools/notes.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2>Notes List</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><span>Services</span></li>
          <li><span>Tools</span></li>
          <li><span>Notes</span></li>
          <li><span>List</span></li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- Add Notes -->
  <div class="container mt-3">
    <!-- Add Notes -->
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button
            class="accordion-button fw-medium"
            type="button"
            style="color: #6610f2"
            data-bs-toggle="collapse"
            data-bs-target="#collapseOne"
            aria-expanded="true"
            aria-controls="collapseOne"
          >
            Add Note <i class="bi bi-pencil-square px-2"></i>
          </button>
        </h2>
        <div
          id="collapseOne"
          class="accordion-collapse collapse"
          aria-labelledby="headingOne"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body d-flex row">
            <form
              action="{% url 'tools:add_note' %}"
              method="post"
              class="d-flex flex-column"
            >
              {% csrf_token %}
              <label for="title" class="w-100">
                <input
                  required
                  type="text"
                  name="title"
                  id=""
                  class="w-100 rounded border p-2"
                  placeholder="write note title"
                />
              </label>
              <label for="note" class="w-100 mt-2">
                <textarea
                  required
                  name="detail"
                  id=""
                  cols="0"
                  rows="5"
                  class="w-100 rounded border p-2"
                  placeholder="write your note detail here"
                ></textarea>
              </label>
              <input
                type="submit"
                value="Save Note"
                class="btn p-2 mt-2"
                style="background-color: #6610f2; color: #fff"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- End Notes -->
    {% for note in notes %}
    <div class="d-flex rounded mt-3 p-2 border justify-content-between">
      <span>
        <a class="" href="{% url 'tools:one_note' note.id%}">{{note.title}}</a>
      </span>
      <span>
        <a class="btn btn-danger" href="{% url 'tools:delete_note' note.id %}">
          Delete
        </a>
      </span>
    </div>
    {% endfor %}
    <br />
  </div>
  <!-- End Notes -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  const header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
  const detailLoader = (content) => {
    document.querySelector(".detail").value = content;
  };
</script>

{% endblock %}

tools/templates/tools/upload.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2>Transcriber</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><span>Tools</span></li>
          <li><span>Transcriber</span></li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- Add Notes -->
  <div class="d-flex justify-content-center">
    <div class="container m-3 ">
        <h1>Upload an Audio File</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{ audio_form.as_p }} {{ options_form.as_p }}
          <input
          id="submit-btn"
            type="submit"
            onclick="dis"
            value="Upload and Transcribe"
            class="btn p-2 mt-2"
            style="background-color: #6610f2; color: #fff"
                  />
        </form>
      </div>
  </div>
</div>
<!-- End Notes -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
const header = document.querySelector("#header");
header.style.background = "rgba(24, 6, 185, 0.8)";
const detailLoader = (content) => {
  document.querySelector(".detail").value = content;
};

document.querySelector('#submit-btn').addEventListener('click', () => {
    alert("Processing, it may take 15%-30% of the file's duration, eg a 10 minute file takes 90-180 seconds to complete. After that, your transcription will automatically be downloaded.")
})
</script>

{% endblock %}