blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='comment/', view=views.comment, name='comment'),
    path(route='search/', view=views.search, name='search'),
    path(route='update-blogs/', view=views.updateBlogs, name='update_blogs'),
    # path(route='hashnode-blogs', view=views.hashnodeBlogs, name='hashnode_blogs'), 
]

dataidea/urls.py
from django.urls import path
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path(route = 'admin/', view=admin.site.urls),
    path(route='', view=include('index.urls'), name='index'),
    path(route='blog/', view=include('blog.urls'), name='blog'),
    path(route='school/', view=include('school.urls'), name='school'),
    path(route='profiles/', view=include('profiles.urls'), name='profiles'),
    path(route='accounts/', view=include('accounts.urls'), name='accounts'),
    path(route='tools/', view=include('tools.urls'), name='tools')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from . import views
from django.urls import path
from django.urls import include

app_name = 'index'

urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='back/', view=views.back, name='back'),
    path(route='school/', view=include('school.urls'), name='school'),
    path(route='feedback/', view=views.feedback, name='feedback'),
    path(route='terms_of_service', view=views.termsOfService, name='terms_of_service'),
    path(route='privacy_policy', view=views.privacyPolicy, name='privacy_policy'),
    path(route='portfolio_details/<int:id>', view=views.portfolio_details, name='portfolio_details')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here
class Author(models.Model):
    name = models.CharField(max_length=122, default='dataidea')
    email = models.CharField(max_length=122, default='datasideaofficial@gmail.com')
    profile = models.CharField(max_length=122, default='No profile provided')

    def __str__(self):
        return self.name
    
class BlogCategory(models.Model):
    name = models.CharField(max_length=122, default='New category')
    description = models.CharField(max_length=122, default='New category description')
    color = models.CharField(max_length=122, default='purple')

    def __str__(self):
        return self.name
    
    
class Blog(models.Model):
    slug = models.CharField(max_length=122, default='New Blog Slug')
    cuid = models.CharField(max_length=122, default='New Cuid')
    title = models.CharField(max_length=122)
    author = models.ForeignKey(to=Author, on_delete=models.CASCADE, default=1)
    category = models.ForeignKey(to=BlogCategory, on_delete=models.CASCADE, default=1)
    brief = models.TextField(default='')
    cover_image = models.CharField(max_length=122, default='no image')
    popularity = models.FloatField(default=0)
    date_featured = models.CharField(max_length=122, default='no date', null=True)
    content_markdown = models.TextField(default='')

    def __str__(self):
        return self.title
    
    
class BlogComment(models.Model):
    approved = models.BooleanField(default=False) 
    comment = models.TextField(default='New Comment')
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, default=12)
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.comment

blog/views.py
import requests
import markdown
from . models import Blog
from django.db.models import Q
from . models import BlogComment
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.core.paginator import Paginator

# Create your views here.
# def blogs(request):
#     context = {}
#     return render(request, 'blog/blogs.html')


def updateBlogs(request):
    username = 'jumashafara'
    page = 1
    all_blogs = []

    while True:
        query = """
        query GetAllBlogsByUser($username: String!, $page: Int) {
            user(username: $username) {
                publication {
                    posts (page:  $page){
                        slug
                        cuid
                        title
                        brief
                        coverImage
                        popularity
                        dateFeatured
                        contentMarkdown
                    }
                }
            }
        }
        """
        variables = {
            "username": username,
            "page": page
        }

        response = requests.post(
            "https://api.hashnode.com",
            json={"query": query, "variables": variables},
        )

        data = response.json()['data']['user']['publication']['posts']
        all_blogs.extend(data)

        if len(data) == 0:
            break
        else:
            page += 1

    for blog in all_blogs:
        if not Blog.objects.filter(cuid=blog['cuid']).exists():
            new_blog = Blog(
                slug=blog['slug'],
                cuid=blog['cuid'],
                title=blog['title'],
                brief=blog['brief'],
                cover_image=blog['coverImage'],
                popularity=blog['popularity'],
                date_featured=blog['dateFeatured'],
                content_markdown=blog['contentMarkdown'],
                )
            new_blog.save()
        else:
            update = Blog.objects.get(cuid=blog['cuid'])
            update.title=blog['title']
            update.brief=blog['brief']
            update.cover_image=blog['coverImage']
            update.popularity=blog['popularity']
            update.date_featured=blog['dateFeatured']
            update.content_markdown=blog['contentMarkdown']
            update.save()

    context = {'state': 'success', 'message': 'Updated blogs'}
    template_name = 'components/message.html'
    return render(request=request, template_name=template_name, context=context)


def blogs(request):
    # Fetch Blogs
    blogs = Blog.objects.all()

    # Sort
    sorted_blogs = sorted(blogs, key=lambda k: k.popularity, reverse=True)

    # pagination
    paginator = Paginator(sorted_blogs, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'blogs': page_obj}
    template_name = 'blog/blogs.html'
    return render(request=request, template_name=template_name, context=context)


def blogDetails(request):
    # Fetch Blog Details
    try:
        blog = Blog.objects.get(slug=request.GET.get('slug'))
        related = Blog.objects.filter(category=blog.category)
    except Blog.DoesNotExist:
        context = {'state': 'danger', 'message': 'Blog not found'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)
    # Fetch Blog Comments
    comments = BlogComment.objects.filter(blog=blog)

    
    context = {
        'blog': blog, 
        'details': markdown.markdown(blog.content_markdown), 
        'comments': comments,
        'related': related[:4]
        }
    return render(request, 'blog/blog_details.html', context=context)


# Comments
def comment(request):

    if request.user.is_anonymous:
        user = User.objects.get(id=12)
    else:
        user = request.user

    try:
        comment = BlogComment(
            comment = request.POST.get(key='comment'),
            blog = Blog.objects.get(slug=request.POST.get(key='slug')),
            user = user
        )

        comment.save()
        return redirect(request.META.get('HTTP_REFERER'))
    except Exception as e:
        print(e)
        context = {'message': 'An error occured while trying to add your comment', 'state':  'danger'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)
    

def search(request):
    query = request.POST.get(key='query')
    blogs = Blog.objects.filter(
        Q(title__icontains=query) |
        Q(content_markdown__icontains=query)|
        Q(category_id=query)
    )

     # Sort
    sorted_blogs = sorted(blogs, key=lambda k: k.popularity, reverse=True)

     # pagination
    # paginator = Paginator(sorted_blogs, 4)
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)

    context = {'blogs': sorted_blogs}
    template_name = 'blog/blogs.html'
    return render(request=request, template_name=template_name, context=context)

blog/templates/blog/blog_details.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="p-2">{{blog.title}}</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'blog:blogs' %}">Blogs</a></li>
          <li><span>{{blog.title}}</span></li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-8">
          <div class="portfolio-details-slider swiper">
            <div class="swiper-wrapper align-items-center">
              <div class="swiper-slide">
                <img src="{{blog.cover_image}}" alt="" />
              </div>
            </div>
            <div class="swiper-pagination"></div>
          </div>
          <div class="portfolio-description">
            <!-- <h2>Project Description</h2> -->
            {{details|safe}}
          </div>
          <!-- Comments -->
          <div class="portfolio-info">
            <h3>Comments</h3>
            <ul>
              {% for comment in comments %}
              <li>
                <strong>
                  <!-- End of staff -->
                  {{comment.user}}
                  <!-- If usesr is verified -->
                  {% for group in comment.user.groups.all %}
                  <!-- Check for Verified -->
                  {% if group.name == 'Verified' %}
                  <i class="bi bi-patch-check"></i>
                  {% endif %} {% endfor %}
                  <!-- If usesr is staff -->
                  {% if comment.user.is_staff %}
                  <!-- staff -->
                  (staff) {% endif %}
                </strong>
                {{comment.comment}}
              </li>
              {% endfor %}
            </ul>
            <form
              action="{% url 'blog:comment' %}"
              method="post"
              class="d-flex flex-column"
            >
              {% csrf_token %}
              <input type="hidden" name="slug" value="{{blog.slug}}" />
              <label for="comment" class="w-100">
                <input
                  type="text"
                  name="comment"
                  id=""
                  class="w-100 rounded border p-2"
                  placeholder="&#64;{{user}} write your comment here"
                />
              </label>
              <input
                type="submit"
                value="Comment"
                class="btn p-2 mt-2"
                style="background-color: #6610f2; color: #fff"
              />
            </form>
          </div>
          <!-- End of Comments -->
        </div>
        <div class="col-lg-4">
          <div class="portfolio-info">
            <h3>Blog information</h3>
            <ul>
              <li><strong>Title</strong>: {{blog.title}}</li>
              <li><strong>Author</strong>: {{blog.author}}</li>
              <li><strong>Category</strong>: {{blog.category}}</li>
            </ul>
          </div>
          <!-- Similar -->
          <div class="">
            <h3
              class="mt-3"
              style="
                padding: 30px;
                font-size: 22px;
                font-weight: 700;
                margin-bottom: 20px;
                padding-bottom: 20px;
                border-bottom: 1px solid #eee;
              "
            >
              You may also like:
            </h3>
            {% if related %}
            <!-- For Each Relative -->
            {% for relative in related %}
            <!-- If not self -->
            {% if not relative.id == blog.id %}
            <div
              class="mt-3"
              style="
                padding: 30px;
                box-shadow: 0px 0 30px rgba(44, 73, 100, 0.08);
              "
              data-aos="fade-up"
              data-aos-delay="100"
            >
              <a href="{% url 'blog:blog_details'%}?slug={{relative.slug}}"
                class="nav-link">
                  <img src="{{relative.cover_image}}"
                  class="img-fluid rounded"
                  alt="" />
                  <h5 class="mt-3">{{ relative.title }}</h5>
                </a>
            </div>
            {% endif %} {% endfor %}
            <!-- Otherwise -->
            {% else %}
            <h5>No related found</h5>
            {% endif %}

            <div>
              <form
                action="{% url 'blog:search'%}"
                method="post"
                class="d-flex mt-3"
              >
                {% csrf_token %}
                <label for="query" class="">
                  <input
                    hidden
                    type="text"
                    name="query"
                    id=""
                    class="w-100 rounded border p-2"
                    value="{{blog.category.id}}"
                  />
                </label>
                <input
                  type="submit"
                  value="See more"
                  class="btn p-2 w-100"
                  style="background-color: #6610f2; color: #fff"
                />
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Portfolio Details Section -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";

  // Wait for the DOM to be fully loaded
  document.addEventListener("DOMContentLoaded", function () {
    // Get the image element
    var imgs = document.querySelectorAll("img");

    // Check if the image element exists
    if (imgs) {
      imgs.forEach((img) => {
        // Get the original src attribute
        var originalSrc = img.getAttribute("src");
        // Remove everything from 'align' onwards
        var newSrc = originalSrc.split(" align=")[0];
        // Set the new src attribute
        img.setAttribute("src", newSrc);
        img.classList.add("img-fluid");
      });
    }
  });
</script>

{% endblock %}

blog/templates/blog/blogs.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2>Blogs</h2>
        <ol>
          <li><a href="{% url 'index:home' %}">Home</a></li>
          <li>Blogs</li>
        </ol>
        <form
              action="{% url 'blog:search'%}"
              method="post"
              class="d-flex mt-2"
            >
              {% csrf_token %}
              <label for="query" class="">
                <input
                  type="text"
                  name="query"
                  id=""
                  class="w-100 rounded border p-2"
                  placeholder="&#64;{{user}} search blogs"
                />
              </label>
              <input
                type="submit"
                value="Search"
                class="btn p-2 mx-2"
                style="background-color: #6610f2; color: #fff"
              />
            </form>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <section class="inner-page" style="padding: 0;" >
    <!-- Popular Courser -->
      <div id="pricing" class="pricing section-bg">
        <div class="container p-3" data-aos="fade-up">
          <div class="section-title">
            <h2>Popular Blogs</h2>
            <p>
              Explore the world of Machine Learning, Web Development, Statistics, 
              and more with our insightful blog posts. Our dedicated team of experts 
              shares valuable knowledge, practical tips, 
              and the latest trends to help you stay informed and empowered.
            </p>
          </div>
    
   
          <div class="row">
            {% if blogs %}
            {% for blog in blogs %}
            <div class="col-lg-3 col-md-6 mt-5" data-aos="fade-up" data-aos-delay="100">
              <!-- <div class=""> -->
                <a href="{% url 'blog:blog_details'%}?slug={{blog.slug}}"
                class="nav-link">
                  <img src="{{blog.cover_image}}" 
                  class="img-fluid rounded"
                  alt="" />
                  <h5 class="mt-3">{{ blog.title }}</h5>
                </a>
              <!-- </div> -->
            </div>
            {% endfor %}
            <!-- Otherwise -->
            {% else %}
            <h5>No blogs found</h5>
            {% endif %}
          </div>
          <!-- Pagination -->
          <div class="pagination col-md-6 m-auto">
            <span
              class="step-links d-flex justify-content-between p-3 border m-2 mt-3 rounded w-100" 
              style="background: whitesmoke;"
            >
              {% if blogs.has_previous %}
              <a href="?page=1">&laquo; First</a>
              <a href="?page={{ blogs.previous_page_number }}">Previous</a>
              {% endif %}

              <span class="current">
                Page {{ blogs.number }}
                <!-- Current number -->
                of
                <!-- Total number -->
                {{ blogs.paginator.num_pages}}.
              </span>

              {% if blogs.has_next %}
              <a href="?page={{ blogs.next_page_number }}">Next</a>
              <a href="?page={{ blogs.paginator.num_pages }}"
                >Last &raquo;</a
              >
              {% endif %}
            </span>
          </div>
          <!-- End of Pagination -->
        </div>
  </section>
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  document.querySelector("#header").style.background = "rgba(24, 6, 185, 0.8)";

  document.querySelector(".school").classList.add("active");
</script>
{% endblock %}