accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path(route="signup", view=views.signup, name="signup"),
    path(route="signin", view=views.signin, name="signin"),
    path(route="signout", view=views.signout, name="signout")
]

blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='comment/', view=views.comment, name='comment'),
    path(route='search/', view=views.search, name='search'),
    path(route='update-blogs/', view=views.updateBlogs, name='update_blogs'),
    # path(route='hashnode-blogs', view=views.hashnodeBlogs, name='hashnode_blogs'), 
]

dataidea/urls.py
from django.urls import path
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path(route = 'admin/', view=admin.site.urls),
    path(route='', view=include('index.urls'), name='index'),
    path(route='blog/', view=include('blog.urls'), name='blog'),
    path(route='school/', view=include('school.urls'), name='school'),
    path(route='profiles/', view=include('profiles.urls'), name='profiles'),
    path(route='accounts/', view=include('accounts.urls'), name='accounts'),
    path(route='tools/', view=include('tools.urls'), name='tools')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from . import views
from django.urls import path
from django.urls import include

app_name = 'index'

urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='back/', view=views.back, name='back'),
    path(route='school/', view=include('school.urls'), name='school'),
    path(route='feedback/', view=views.feedback, name='feedback'),
    path(route='terms_of_service', view=views.termsOfService, name='terms_of_service'),
    path(route='privacy_policy', view=views.privacyPolicy, name='privacy_policy'),
    path(route='portfolio_details/<int:id>', view=views.portfolio_details, name='portfolio_details')
]

school/urls.py
from django.urls import path
from . import views

app_name = 'school'

urlpatterns = [
    path(route='', view=views.browse, name='browse'),
    path(route='search_courses/', view=views.searchCourses, name='search_courses'),
    path(route='comment/<int:id>', view=views.comment, name='comment'),
    path(route='course-details/<int:id>', view=views.course_details, name='course_details'),
    path(route='quiz/<int:quiz_id>/', view=views.quiz_view, name='quiz'),

]

tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path(route='transcriber/upload/', view=views.upload_file, name='upload_transcribe_file'),
    path(route='transcriber/download/<int:pk>/<str:option>/', view=views.download_transcription, name='download_transcription'),
    path(route='note/add_note/', view=views.add_note, name='add_note'),
    path(route='note/delete_note/<int:id>', view=views.delete_note, name='delete_note'),
    path(route='note/one_note/<int:id>', view=views.one_note, name='one_note'),
]

templates/components/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>DataIdea</title>
    <!-- Google analytics tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZD84FCME05"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-ZD84FCME05');
    </script>
    <!-- End of Google Analytics tag -->
    
    <!--Google Ads-->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8076040302380238"
     crossorigin="anonymous"></script>
    <meta
      content="At Data Idea, we are committed to helping businesses harness the power of data to drive growth and innovation. Our team of skilled professionals specializes in providing comprehensive data-driven solutions that empower organizations to make informed decisions and achieve their goals."
      name="description"
    />
    <!--End of Google Ads-->

    <meta content="dataidea data idea uganda" name="keywords" />

    <!-- Favicons -->
    <link href="{% static 'img/dataidea.png' %}" rel="icon" />
    <link href="{% static 'img/dataidea.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/boxicons/css/boxicons.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/swiper/swiper-bundle.min.css' %}"
      rel="stylesheet"
    />

    <!-- Template Main CSS File -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
      <div class="container d-flex align-items-center justify-content-between">
        <h1 class="logo"><a href="{% url 'index:home' %}">DataIdea</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo"><img src="{% static 'img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar">
          <ul>
            <li>
              <a
                class="nav-link scrollto home"
                href="{% url 'index:home' %}#hero"
                >Home</a
              >
            </li>
            <li class="dropdown">
              <a href="#"
                ><span>About</span> <i class="bi bi-chevron-down"></i
              ></a>
              <ul>
                <li>
                  <a
                    class="nav-link scrollto"
                    href="{% url 'index:home' %}#about"
                    >About Us</a
                  >
                </li>
                <li>
                  <a
                    class="nav-link scrollto"
                    href="{% url 'index:home' %}#portfolio"
                    >Portfolio</a
                  >
                </li>
                <li>
                  <a
                    class="nav-link scrollto"
                    href="{% url 'index:home' %}#partners"
                    >Partners</a
                  >
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#"
                ><span>Services</span> <i class="bi bi-chevron-down"></i
              ></a>
              <ul>
                <li>
                  <a
                    class="nav-link scrollto"
                    href="{% url 'index:home' %}#services"
                    >Our Services</a
                  >
                </li>
                <li class="dropdown">
                  <a href=""
                    ><span>Our Tools</span> <i class="bi bi-chevron-right"></i
                  ></a>
                  <ul>
                    <li><a href="{% url 'tools:add_note' %}">Notes</a></li>
                    <li>
                      <a href="{% url 'tools:upload_transcribe_file' %}"
                        >Transcriber</a
                      >
                    </li>
                    <!-- <li><a href="">Video and Course Finder</a></li> -->
                  </ul>
                </li>
              </ul>
            </li>
            <li>
              <a
                class="nav-link scrollto services"
                href="{% url 'school:browse' %}"
                >Courses</a
              >
            </li>
            <li class="dropdown">
              <a href="#"
                ><span>Resources</span> <i class="bi bi-chevron-down"></i
              ></a>
              <ul>
                <li>
                  <a class="nav-link scrollto" href="{% url 'blog:blogs' %}"
                    >Blog</a
                  >
                </li>
                <li>
                  <a
                    class="nav-link scrollto"
                    target="_blank"
                    href="https://dataideaforum.pythonanywhere.com/"
                    >Forum</a
                  >
                </li>
                <li>
                  <a
                    class="nav-link scrollto"
                    href="{% url 'index:home' %}#newsletter"
                    >Newsletter</a
                  >
                </li>
              </ul>
            </li>
            <li>
              <a class="nav-link scrollto" href="{% url 'index:home' %}#contact"
                >Contact</a
              >
            </li>
            <li>
              <a
                class="nav-link scrollto"
                href="https://dataideaforum.pythonanywhere.com/"
                >Forum</a
              >
            </li>
            <li class="dropdown">
              <a href="#"
                ><span>Account</span> <i class="bi bi-chevron-down"></i
              ></a>
              <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:signout' %}">Signout</a></li>
                <li><a href="/admin">Administer</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signin' %}">Signin</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <!-- .navbar -->
      </div>
    </header>
    <!-- End Header -->
    {% block content %}{% endblock %}
    <!-- ======= Footer ======= -->
    <footer id="footer">
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-6 footer-contact">
              <h3>Data Idea</h3>
              <p>
                Plot 160 <br />
                UMF House <br />
                3rd Floor <br />
                Sir Apollo Kaggwa Rd, Kampala<br />
                Uganda <br /><br />
                </p>
            </div>

            <div class="col-lg-2 col-md-6 footer-links">
              <h4>Useful Links</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="{% url 'index:home' %}#home">Home</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="{% url 'index:home' %}#about">About us</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="{% url 'index:home' %}#services">Services</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="{% url 'index:terms_of_service'%}"
                    >Terms of service</a
                  >
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="{% url 'index:privacy_policy' %}">Privacy policy</a>
                </li>
              </ul>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
              <h4>Our Services</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <span>Research</span>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <span>Data Analysis and Visualization</span>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <span>ML Model and Systems Development</span>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <span>Software Development</span>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="{% url 'school:browse' %}"
                    >Free Learning Courses and Materials(Click to browse)</a
                  >
                </li>
              </ul>
            </div>

            <div class="col-lg-4 col-md-6 footer-newsletter">
              <iframe
                src="https://embeds.beehiiv.com/5fc7c425-9c7e-4e08-a514-ad6c22beee74"
                data-test-id="beehiiv-embed"
                width="100%"
                height="320"
                frameborder="0"
                scrolling="no"
                style="
                  border-radius: 4px;
                  border: 2px solid #e5e7eb;
                  margin: 0;
                  background-color: transparent;
                "
              ></iframe>
            </div>
          </div>
        </div>
      </div>

      <div class="container" id="newsletter">
        <div class="copyright-wrap d-md-flex py-4">
          <div class="me-md-auto text-center text-md-start">
            <div class="copyright">
              &copy; Copyright <strong><span>DataIdeaUg</span></strong
              >. All Rights Reserved
            </div>
            <div class="credits">
              Designed by
              <a href="https://jumashafara.github.io">Juma Shafara</a>
            </div>
          </div>
          <div class="social-links text-center text-md-right pt-3 pt-md-0">
            <a href="https://twitter.com/datas_idea" class="twitter"
              ><i class="bx bxl-twitter"></i
            ></a>
            <a
              href="https://www.facebook.com/profile.php?id=100079727257708"
              class="facebook"
              ><i class="bx bxl-facebook"></i
            ></a>
            <a href="https://www.youtube.com/@dataidea2347" class="youtube"
              ><i class="bx bxl-youtube"></i
            ></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- End Footer -->

    <a
      href=""
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/components/button.html
<div class="btn btn-wrap">
  <a href="{{href}}" onclick="{{onclick}}" class="btn-buy">{{value}}</a>
</div>

templates/components/details.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        {% include button %}

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img src="assets/img/portfolio/portfolio-1.jpg" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="assets/img/portfolio/portfolio-2.jpg" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="assets/img/portfolio/portfolio-3.jpg" alt="">
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="portfolio-info">
              <h3>Project information</h3>
              <ul>
                <li><strong>Category</strong>: Web design</li>
                <li><strong>Client</strong>: ASU Company</li>
                <li><strong>Project date</strong>: 01 March, 2020</li>
                <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
              </ul>
            </div>
            <div class="portfolio-description">
              <h2>Description</h2>
              <p>
                Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.
              </p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Techie</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container">

      <div class="copyright-wrap d-md-flex py-4">
        <div class="me-md-auto text-center text-md-start">
          <div class="copyright">
            &copy; Copyright <strong><span>Techie</span></strong>. All Rights Reserved
          </div>
          <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/techie-free-skin-bootstrap-3/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>

templates/components/filter-display.html
<div class="row">
  <div class="col-lg-12 d-flex justify-content-center">
    <ul id="portfolio-flters">
      <li data-filter="*" class="filter-active">All</li>
      <li data-filter=".filter-app">App</li>
      <li data-filter=".filter-tutorial">Tutorials</li>
      <li data-filter=".filter-web">Web</li>
    </ul>
  </div>
</div>

<div class="row portfolio-container">
  {% if portfolios %}
  <!-- Display Portfolio -->
  {% for portfolio in portfolios %}
  <div class="col-lg-4 col-md-6 portfolio-item filter-{{portfolio.category}}">
    <a
      href="https://colab.research.google.com/drive/1ysvJ_OyGYrTO2zgPDfvPOMN98S6inFix"
      target=""
      title="More Details"
    >
      <div class="portfolio-wrap">
        <img src="{{portfolio.image.url}}" class="img-fluid" alt="" />
        <div class="portfolio-info">
          <h4>{{portfolio.name}}</h4>
          <p>{{portfolio.category}}</p>
        </div>
        <div class="portfolio-links">
          <a
            href="{{portfolio.image.url}}"
            data-gallery="portfolioGallery"
            class="portfolio-lightbox"
            title="Card 2"
            ><i class="bx bx-plus"></i
          ></a>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
  <!-- End of Portfolios -->
  {% else %}
  <div>No Portfolio</div>
  {% endif %}
</div>

templates/components/message.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="p-2">Message</h2>
        <ol>
          <li>Message</li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">
      <div
        class="message-container bg-{{state}} p-3 rounded"
        style="color: #fff"
      >
        {{message}}
        <span
          class=""
          style="color: orange; text-decoration: underline; cursor: pointer"
          onclick="history.back()"
          >Click here to go back</span
        >
      </div>
    </div>
  </section>
  <!-- End Portfolio Details Section -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
</script>

{% endblock %}