blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='comment/', view=views.comment, name='comment'),
    path(route='search/', view=views.search, name='search'),
    path(route='update-blogs/', view=views.updateBlogs, name='update_blogs'),
    # path(route='hashnode-blogs', view=views.hashnodeBlogs, name='hashnode_blogs'), 
]

dataidea/urls.py
from django.urls import path
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path(route = 'admin/', view=admin.site.urls),
    path(route='', view=include('index.urls'), name='index'),
    path(route='blog/', view=include('blog.urls'), name='blog'),
    path(route='school/', view=include('school.urls'), name='school'),
    path(route='profiles/', view=include('profiles.urls'), name='profiles'),
    path(route='accounts/', view=include('accounts.urls'), name='accounts'),
    path(route='tools/', view=include('tools.urls'), name='tools')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from . import views
from django.urls import path
from django.urls import include

app_name = 'index'

urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='back/', view=views.back, name='back'),
    path(route='school/', view=include('school.urls'), name='school'),
    path(route='feedback/', view=views.feedback, name='feedback'),
    path(route='terms_of_service', view=views.termsOfService, name='terms_of_service'),
    path(route='privacy_policy', view=views.privacyPolicy, name='privacy_policy'),
    path(route='portfolio_details/<int:id>', view=views.portfolio_details, name='portfolio_details')
]

school/urls.py
from django.urls import path
from . import views

app_name = 'school'

urlpatterns = [
    path(route='', view=views.browse, name='browse'),
    path(route='search_courses/', view=views.searchCourses, name='search_courses'),
    path(route='comment/<int:id>', view=views.comment, name='comment'),
    path(route='course-details/<int:id>', view=views.course_details, name='course_details'),
    path(route='quiz/<int:quiz_id>/', view=views.quiz_view, name='quiz'),

]

tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path(route='transcriber/upload/', view=views.upload_file, name='upload_transcribe_file'),
    path(route='transcriber/download/<int:pk>/<str:option>/', view=views.download_transcription, name='download_transcription'),
    path(route='note/add_note/', view=views.add_note, name='add_note'),
    path(route='note/delete_note/<int:id>', view=views.delete_note, name='delete_note'),
    path(route='note/one_note/<int:id>', view=views.one_note, name='one_note'),
]

school/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Tutor(models.Model):
    name = models.CharField(max_length=122, default='New Tutor')
    info = models.CharField(max_length=122, default='New Tutor')
    
    def __str__(self):
        return self.name
    
class Organization(models.Model):
    name = models.CharField(max_length=122, default='DataIdea')
    url = models.CharField(max_length=122, default='dataidea.com')

    def __str__(self):
        return self.name
    

class Comment(models.Model):
    approved = models.BooleanField(default=False) 
    comment = models.TextField(default='New Comment')
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, default=12)
    def __str__(self):
        return self.comment
    

class Quiz(models.Model):
    name = models.CharField(max_length=255, default='New Quiz')
    description = models.TextField(null=True, blank=True)
    # Add any other fields you need for your quiz

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(to=Quiz, on_delete=models.CASCADE, 
        related_name='questions', null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    # Add any other fields you need for your questions
    
    def __str__(self):
        return self.text

class Choice(models.Model):
    question = models.ForeignKey(to=Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)
    # Add any other fields you need for choices
    
    def __str__(self):
        return f'{self.question}, {self.text}, {self.is_correct}' 


class Video(models.Model):
    name = models.CharField(max_length=122, default='New Video')
    url = models.CharField(max_length=122, default='New Video')
    gist = models.CharField(max_length=122, default='New Gist')
    comments = models.ManyToManyField(to=Comment, default=None)
    quiz = models.OneToOneField(to=Quiz, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.name
    

class Course(models.Model):
    LEVELS = [('reception-1', 'Beginner'), ('reception-2', 'Intermediate'), ('reception-3', 'Advanced'), ('reception-4', 'Explorer'),]
    name = models.CharField(max_length=122, default='New Course')
    description = models.TextField(default='New Course')
    image = models.ImageField(upload_to='course_images/', default='images/default.jpg')
    organization = models.ForeignKey(to=Organization, default=0, on_delete=models.CASCADE)
    tutors = models.ManyToManyField(to=Tutor, default='Not Identified')
    url = models.CharField(max_length=122, default='No URLs provided attached')
    level = models.CharField(max_length=22, choices=LEVELS, default='reception-1')
    learners = models.IntegerField(default=0)
    videos = models.ManyToManyField(to=Video, default='No Videos')
    quiz = models.OneToOneField(to=Quiz, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class Learner(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    courses = models.ManyToManyField(to=Course)
    subscription_end = models.DateField(null=True)

    def __str__(self):
        return self.user.username



    

school/views.py
from .models import Quiz
from .models import Video
from .models import Course
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

# Create your views here.

def quiz_view(request, quiz_id):
    try:
        quiz = Quiz.objects.get(pk=quiz_id)
    except Quiz.DoesNotExist:
        context = {'message': 'Quiz Not Found', 'state': 'danger'}
        template_name = 'components/message.html'
        return render (request=request, 
                       template_name=template_name, 
                       context=context)
    questions = quiz.questions.all()

    # Calculate correct answers for each question
    correct_answers = {}
    for question in questions:
        correct_choices = question.choice_set.filter(is_correct=True)
        correct_answers[f'{question.id}'] = [choice.text for choice in correct_choices]

    if request.method == 'POST':
        score = 0

        for question in questions:
            selected_choice_id = request.POST.get(f'question_{question.id}', None)
            if selected_choice_id:
                selected_choice = question.choice_set.get(pk=selected_choice_id)

                # Check if the selected choice is correct
                if selected_choice.is_correct:
                    score += 1

        # You can also store the user's score in the user's profile or a separate model here

        return render(request, 'school/results.html',
                      {'quiz': quiz, 'questions': questions,
                       'score': score, 'correct_answers': correct_answers})

    return render(request, 'school/quiz.html', {'quiz': quiz, 'questions': questions})


def browse(request):
    courses = Course.objects.all().order_by('-pk')
    course_level_key_map = {'reception-1': 'Introduction'}

    # pagination
    paginator = Paginator(courses, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'courses': page_obj,
               'course_level_key_map': course_level_key_map}
    template_name = 'school/browse.html'
    return render(request=request, 
                  template_name=template_name,
                   context=context )


def searchCourses(request):
    query = request.POST.get(key='query')

    if query:
        courses = Course.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )
        course_level_key_map = {'reception-1': 'Introduction'}
        context = {'courses': courses,
                'course_level_key_map': course_level_key_map}
        template_name = 'school/browse.html'
        return render(request=request, 
                    template_name=template_name,
                    context=context )
    
    elif query == '' or query == None:
        return redirect('school:browse')

# @login_required(login_url='accounts:signin')
def course_details(request, id):
    course = Course.objects.get(id=id)
    videos = course.videos.all()

    # pagination
    paginator = Paginator(videos, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'course': course,
               'videos': page_obj,
               'user': request.user}
    template_name = 'school/course_details.html'
    return render(request=request, 
                  template_name=template_name, 
                  context=context)


def comment(request, id):
    try:
        video = Video.objects.get(id=id)
        comment = request.POST['comment']
        user = request.user
        if user.is_anonymous:
            video.comments.create(comment=comment)
            message = """
                    Thanks for your comment! Please sign in to enjoy the full benefits of our services. 
                    Your comment has been saved and will be visible to other users after you refresh the page 😊.
                    """
            context = {'message': message, 'state': 'success'}
            template_name = 'components/message.html'
            return render(request=request, template_name=template_name, context=context)
        else:
            video.comments.create(comment=comment, user=user)
            return redirect(request.META.get('HTTP_REFERER'))
    except Exception as e:
        message = """
                    Sorry, something went wrong while saving your comment. 
                    Please try again later.
                    """
        context = {'message': message, 'state': 'warning'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)






# http://127.0.0.1:8000/schoolcourse-details/3?page=2

school/templates/school/browse.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2>School</h2>
        <ol>
          <li><a href="{% url 'index:home' %}">Home</a></li>
          <li>School</li>
        </ol>
        <form
              action="{% url 'school:search_courses'%}"
              method="post"
              class="d-flex mt-2"
            >
              {% csrf_token %}
              <label for="query" class="">
                <input
                  type="text"
                  name="query"
                  id=""
                  class="w-100 rounded border p-2"
                  placeholder="&#64;{{user}} search courses"
                />
              </label>
              <input
                type="submit"
                value="Search"
                class="btn p-2 mx-2"
                style="background-color: #6610f2; color: #fff"
              />
            </form>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <section class="inner-page" style="padding: 0;" >
    <!-- Popular Courser -->
      <div id="pricing" class="pricing section-bg">
        <div class="container p-3" data-aos="fade-up">
          <div class="section-title">
            <h2>Popular Courses</h2>
            <p>
              Dive into the world of Web Development and Machine Learning with our curated courses and tutorials. From beginner to expert, learn from industry professionals and master the latest skills. Start your journey to innovation today!
            </p>
          </div>
    
   
          <div class="row">
            {% if courses %}
            {% for course in courses %}
            <div class="col-lg-3 col-md-6 mt-3" data-aos="fade-up" data-aos-delay="100">
              <div class="box">
                <h3>{{course.name}}</h3>
                <ul>
                  <li class="">
                    <i class="bi bi-{{course.level}}"></i>
                    <span>
                      {% if course.level == 'reception-1'%}
                    Beginner
                    {% elif course.level == 'reception-2'%}
                    Intermediate
                    {% elif course.level == 'reception-3'%}
                    Advanced
                    {% elif course.level == 'reception-4'%}
                    Explorer
                    {% else %}
                    {{course.level}}
                    {% endif %}
                    </span>
                  </li>
                  <li class="">
                    <i class="bi bi-buildings-fill"></i>
                    <span>{{course.organization}}</span>
                  </li>
                  <li class="">
                    <i class="bi bi-person-fill"></i>
                    <span>
                      {% for tutor in course.tutors.all %}
                      {{tutor.name}},
                      {% endfor %}
                    </span>
                  </li>
                </ul>
                <div class="btn-wrap">
                  <a href="{% url 'school:course_details' course.id %}" class="btn-buy">GET STARTED</a>
                </div>
              </div>
            </div>
            {% endfor %}
            <!-- Otherwise -->
            {% else %}
            <h5>No courses found</h5>
            {% endif %}
          </div>
          <!-- Pagination -->
          <div class="pagination col-md-6 m-auto">
            <span
              class="step-links d-flex justify-content-between p-3 border m-2 mt-3 rounded w-100" 
              style="background: whitesmoke;"
            >
              {% if courses.has_previous %}
              <a href="?page=1">&laquo; First</a>
              <a href="?page={{ courses.previous_page_number }}">Previous</a>
              {% endif %}

              <span class="current">
                Page {{ courses.number }}
                <!-- Current number -->
                of
                <!-- Total number -->
                {{ courses.paginator.num_pages}}.
              </span>

              {% if courses.has_next %}
              <a href="?page={{ courses.next_page_number }}">Next</a>
              <a href="?page={{ courses.paginator.num_pages }}"
                >Last &raquo;</a
              >
              {% endif %}
            </span>
          </div>
          <!-- End of Pagination -->
        </div>
  </section>
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  document.querySelector("#header").style.background = "rgba(24, 6, 185, 0.8)";

  document.querySelector(".school").classList.add("active");
</script>
{% endblock %}

school/templates/school/course_details.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<!-- Load auth -->
<!-- Styles -->
<style>
  .video-wrapper {
    position: relative;
    padding-bottom: 56.25%; /* 16:9 aspect ratio (for 100% width) */
    height: 0;
  }

  .video-iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
</style>
<!-- End of Styles -->

<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="p-2">{{course.name}} Details</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'school:browse'%}">School</a></li>
          <li>{{course.name}} Details</li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-8">
          <div id="portfolio" class="portfolio">
            <div class="container" data-aos="fade-up">
              <!-- Add Notes -->
              <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingOne">
                    <button
                      class="accordion-button fw-medium"
                      type="button"
                      style="color: #6610f2"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapseOne"
                      aria-expanded="true"
                      aria-controls="collapseOne"
                    >
                      Add Note
                      <i class="bi bi-pencil-square px-2"></i>
                    </button>
                  </h2>
                  <div
                    id="collapseOne"
                    class="accordion-collapse collapse"
                    aria-labelledby="headingOne"
                    data-bs-parent="#accordionExample"
                  >
                    <div class="accordion-body d-flex row">
                      <form
                        action="{% url 'tools:add_note' %}"
                        method="post"
                        class="d-flex flex-column"
                      >
                        {% csrf_token %}
                        <label for="title" class="w-100">
                          <input
                            required
                            type="text"
                            name="title"
                            id=""
                            class="w-100 rounded border p-2"
                            placeholder="write note title"
                          />
                        </label>
                        <label for="note" class="w-100 mt-2">
                          <textarea
                            required
                            name="detail"
                            id=""
                            cols=""
                            rows="5"
                            class="w-100 rounded border p-2"
                            placeholder="write your note detail here"
                          ></textarea>
                        </label>
                        <input
                          type="submit"
                          value="Save Note"
                          class="btn p-2 mt-2"
                          style="background-color: #6610f2; color: #fff"
                        />
                      </form>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End Notes -->
              <!-- Pagination -->
              <div class="pagination">
                <span
                  class="step-links d-flex justify-content-between w-100 w-md-50 mb-3 mt-3"
                >
                  {% if videos.has_previous %}
                  <a href="?page=1">&laquo; First</a>
                  <a href="?page={{ videos.previous_page_number }}">Previous</a>
                  {% endif %}

                  <span class="current">
                    {{ videos.number }}
                    <!-- Current number -->
                    of
                    <!-- Total number -->
                    {{ videos.paginator.num_pages}}.
                  </span>

                  {% if videos.has_next %}
                  <a href="?page={{ videos.next_page_number }}">Next</a>
                  <a href="?page={{ videos.paginator.num_pages }}"
                    >Last &raquo;</a
                  >
                  {% endif %}
                </span>
              </div>
              {% for video in videos %}
              <div class="video-wrapper">
                <iframe
                  class="video-iframe"
                  src="{{video.url}}?rel=0&amp;loop=1&amp;autoplay=1"
                  title="YouTube video player"
                  frameborder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;"
                  allowfullscreen
                ></iframe>
              </div>
              <div>
                <div class="d-flex justify-content-between align-items-center">
                  <h5 class="p-3">{{video.name}}</h5>
                  {% if course.quiz %}
                  <a
                    href="{% url 'school:quiz' course.quiz.id %}"
                    class="btn text-white"
                    style="background-color: #6610f2"
                    >Try Quiz</a
                  >
                  {% endif %}
                </div>
                <script src="{{video.gist}}"></script>
              </div>
              <!-- Comments -->
              <div class="portfolio-info">
                <h3>Comments</h3>
                <ul>
                  {% for comment in video.comments.all %}
                  <li>
                    <strong>
                      <!-- End of staff -->
                      {{comment.user}}
                      <!-- If usesr is verified -->
                      {% for group in comment.user.groups.all %}
                      <!-- Check for Verified -->
                      {% if group.name == 'Verified' %}
                      <i class="bi bi-patch-check"></i>
                      {% endif %} {% endfor %}
                      <!-- If usesr is staff -->
                      {% if comment.user.is_staff %}
                      <!-- staff -->
                      (staff) {% endif %}
                    </strong>
                    {{comment.comment}}
                  </li>
                  {% endfor %}
                </ul>
                <form
                  action="{% url 'school:comment' video.id %}"
                  method="post"
                  class="d-flex flex-column"
                >
                  {% csrf_token %}
                  <label for="comment" class="w-100">
                    <input
                      type="text"
                      name="comment"
                      id=""
                      class="w-100 rounded border p-2"
                      placeholder="&#64;{{user}} write your comment here"
                    />
                  </label>
                  <input
                    type="submit"
                    value="Comment"
                    class="btn p-2 mt-2"
                    style="background-color: #6610f2; color: #fff"
                  />
                </form>
              </div>
              <!-- End of Comments -->
              {% endfor %}
            </div>
          </div>
        </div>

        <!-- Course Information -->
        <div class="col-lg-4">
          <div class="portfolio-info">
            <h3>Course information</h3>
            <ul>
              <li><strong>Name</strong>: {{course.name}}</li>
              <li>
                <strong>Level</strong>:
                <!-- Configure level -->
                {% if course.level == 'reception-1'%}
                <span>Beginner</span>
                {% elif course.level == 'reception-2'%}
                <span>Intermediate</span>
                {% elif course.level == 'reception-3'%}
                <span>Advanced</span>
                {% elif course.level == 'reception-4'%}
                <span>Explorer</span>
                {% else %}
                <span>{{course.level}}</span>
                {% endif %}
              </li>
              <li><strong>Offered by</strong>: {{course.organization}}</li>
              <li>
                <strong>Tutors</strong>:
                <!-- display tutors -->
                {% for tutor in course.tutors.all %}
                <a href="{{tutor.info}}">{{tutor.name}},</a>
                {% endfor %}
              </li>
              <li>
                <strong>Outline</strong>:
                <ul>
                  {% for video in course.videos.all %}
                  <li>
                    <span>{{forloop.counter}}.</span>
                    <span
                      ><a
                        href="{% url 'school:course_details' course.id %}?page={{forloop.counter}}"
                        >{{ video.name }}</a
                      ></span
                    >
                  </li>
                  {% endfor %}
                </ul>
              </li>
              <li>
                <strong>Course URL</strong>:
                <a href="{{course.url}}">{{course.url}}</a>
              </li>
            </ul>
          </div>
          <div class="portfolio-description">
            <h2>Course Description</h2>
            <p>{{course.description}}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Portfolio Details Section -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<!-- Add this in your <head> section -->
<script>
  header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
</script>

{% endblock %}

school/templates/school/note_detail.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="p-2">Note Details</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'school:browse' %}">School</a></li>
          <li><span>Tools</span></li>
          <li><a href="{% url 'school:add_note' %}">Note List</a></li>
          <li>Note Details</li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-8">
          <div class="container">
            <h4>{{note.title}}</h4>
            <pre class="p-3" style="background: whitesmoke">
              <p>{{note.detail}}</p>
            </pre>
            <a
              class="btn btn-danger"
              href="{% url 'school:delete_note' note.id %}"
            >
              Delete
            </a>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="portfolio-info">
            <h3>Note information</h3>
            <ul>
              <li><strong>Date created</strong>: {{note.date_created}}</li>
              <li><strong>Created by</strong>: {{note.user.username}}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Portfolio Details Section -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
</script>

{% endblock %}

school/templates/school/notes.html
{% extends 'components/base.html' %}
<!-- Page Content -->
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2>Notes List</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'school:browse' %}">School</a></li>
          <li><span>Tools</span></li>
          <li><span>Notes List</span></li>
        </ol>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- Add Notes -->
  <div class="container mt-3">
    <!-- Add Notes -->
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button
            class="accordion-button fw-medium"
            type="button"
            style="color: #6610f2"
            data-bs-toggle="collapse"
            data-bs-target="#collapseOne"
            aria-expanded="true"
            aria-controls="collapseOne"
          >
            Add Note <i class="bi bi-pencil-square px-2"></i>
          </button>
        </h2>
        <div
          id="collapseOne"
          class="accordion-collapse collapse"
          aria-labelledby="headingOne"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body d-flex row">
            <form
              action="{% url 'school:add_note' %}"
              method="post"
              class="d-flex flex-column"
            >
              {% csrf_token %}
              <label for="title" class="w-100">
                <input
                  required
                  type="text"
                  name="title"
                  id=""
                  class="w-100 rounded border p-2"
                  placeholder="write note title"
                />
              </label>
              <label for="note" class="w-100 mt-2">
                <textarea
                  required
                  name="detail"
                  id=""
                  cols="0"
                  rows="5"
                  class="w-100 rounded border p-2"
                  placeholder="write your note detail here"
                ></textarea>
              </label>
              <input
                type="submit"
                value="Save Note"
                class="btn p-2 mt-2"
                style="background-color: #6610f2; color: #fff"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- End Notes -->
    {% for note in notes %}
    <div class="d-flex rounded mt-3 p-2 border justify-content-between">
      <span>
        <a class="" href="{% url 'school:one_note' note.id%}">{{note.title}}</a>
      </span>
      <span>
        <a class="btn btn-danger" href="{% url 'school:delete_note' note.id %}">
          Delete
        </a>
      </span>
    </div>
    {% endfor %}
    <br />
  </div>
  <!-- End Notes -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  const header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
  const detailLoader = (content) => {
    document.querySelector(".detail").value = content;
  };
</script>

{% endblock %}